### ISSUE TITLE
Route not found when url's parameters contains dash ('-')

### ISSUE THREAD

**Issue by Etto91** [skipperbent/simple-php-router#233] opened 2017-05-03 10:37 UTC
```php
SimpleRouter::get("/{lang}/products-categories/{name}", function ($lang, $name) {
	include './public/' . $lang . '/products-categories/' . $name . '.html';
});
```

on this route i got an error when the name parameter contains '-' like '/it/products-categories/system-track'.

 '/it/products-categories/system' works.

> Fatal error: Uncaught Pecee\SimpleRouter\Exceptions\NotFoundHttpException: Route not found: /it/products-categories/system-track in /home/vagrant/Code/prima-automotive/vendor/pecee/simple-router/src/Pecee/SimpleRouter/Router.php on line 286

i've tried with this
```php
SimpleRouter::get('/{lang}/products-categories/{name}', function ($lang, $name) {
	include './public/' . $lang . '/products-categories/' . $name . '.html';
})->where(['lang' => '[a-z]', 'name' => '^[A-Za-z0-9\-]+$']);
```

but the problem still remain

**Comment by skipperbent** [comment] 2017-05-09 00:23
I'm pretty sure that this is intended behavior. The default regex for parameters is `%s([\w]+)(\%s?)%s` - so you'll have to customize the regex for the parameters in order to match `-` as `\w` doesn't include this.

The approached you've tried is the right one.

Try this instead:

```php
SimpleRouter::get('/{lang}/products-categories/{name}', function ($lang, $name) {
	include './public/' . $lang . '/products-categories/' . $name . '.html';
})->where(['lang' => '[a-z]+', 'name' => '[A-Za-z0-9\-]+']);
```

**Comment by skipperbent** [comment] 2017-05-09 12:39
I'm closing this issue for now. Please reopen or create a new issue if you have any further questions or issues.

I appreciate your feedback.

/ Simon

**Closed by skipperbent** 2017-05-09 12:39 UTC
